name: go-wave actions Demo
on: [push]
jobs:
  Explore-Github_Actions:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "The job was automatically triggerd by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by Github!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner"
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls -al ${{ github.workspace }}
      - run: chmod +x ./runserver.sh
      - name: run server
        run: ./runserver.sh --dev
      - run: echo "This job's status is ${{ github.status }}."